### ISSUE TITLE
Отсутствует routing.yml

### ISSUE THREAD

**Issue by artemeff** [stfalcon/BlogBundle#1]
`Cannot import resource "@StfalconBlogBundle/Resources/config/routing.yml" from 
"app/config/routing.yml". Make sure the "StfalconBlogBundle" bundle is correctly 
registered and loaded in the application kernel class.`

**Comment by stfalcon** [comment]
они в аннотациях

<pre>StfalconBlogBundle:
    resource: "@StfalconBlogBundle/Controller/"
    type:     annotation
    prefix:   /</pre>
