### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ciprian-cucu** [stfalcon/BlogBundle#21]
Hello,

i tried to install the bundle as instructed. Added "stfalcon/blog-bundle": "*" to json file and then ran php composer.phar update but I got an error:

The requested package stfalcon/blog-bundle could not be found in any version, there may be a typo in the package name.

Am I doing something wrong?

**Comment by GCth** [comment]
use: `"stfalcon/blog-bundle": "dev-master"` or use `"minimum-stability": "dev"` in your composer.json

**Comment by stfalcon** [comment]
yep
